title: Unite and Empower
author: Mr. Durden
email: email@example.com
description: > # this means to ignore newlines until "baseurl:"
  This Side is meant to inspire brave people who want to participate to the building of a better world.
  It shall help the future heros of the climate crisis to live a lifestyle more sustainable, more common 
  and most of all happier as the usual onces ;)
theme: minima


# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
